sudo: false
language: ruby
cache: bundler
rvm:
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - 2.3.0
script: ./script/cibuild
before_install:
  - gem install bundler --pre
  - ./script/bootstrap
notifications:
  email: false
